import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import '../../api/client.dart';
import '../../services/pairing.dart';
import '../../state/auth.dart';
import '../../state/config.dart';

/// Mobile-side: opens the camera, scans a QR generated by HostQrScreen,
/// redeems the pairing token, registers this device as a client, and
/// stores the resulting JWT.
class ScanQrScreen extends ConsumerStatefulWidget {
  const ScanQrScreen({super.key});
  @override
  ConsumerState<ScanQrScreen> createState() => _ScanQrScreenState();
}

class _ScanQrScreenState extends ConsumerState<ScanQrScreen> {
  bool _busy = false;
  String? _error;

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_busy) return;
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null) return;
    final payload = PairingPayload.tryDecode(raw);
    if (payload == null) {
      setState(() => _error = 'Not a Weeber QR code.');
      return;
    }
    if (payload.expired) {
      setState(() => _error = 'QR code expired. Ask the host to refresh.');
      return;
    }
    setState(() {
      _busy = true;
      _error = null;
    });
    try {
      // 1. Redeem pairing token → get account-bound JWT.
      final api = ref.read(apiProvider);
      final redeem = await api.redeemPairingToken(payload.token);
      final token = redeem['token'] as String;

      // 2. Register THIS device as a client.
      const pubkey = 'TODO-pubkey'; // TODO: generate via DeviceKeypair on first run
      final registration = await api.registerDevice(
        token: token,
        name: '${Platform.operatingSystem} client',
        pubkey: pubkey,
        kind: 'client',
      );

      // 3. Persist the (now device-bound) JWT.
      await ref.read(authProvider.notifier).replaceToken(registration.token);
      await ref.read(appConfigProvider.notifier).update(
            (c) => c.copyWith(deviceId: registration.deviceId, onboardingComplete: true),
          );
      if (mounted) context.go('/drive');
    } on ApiException catch (e) {
      setState(() {
        _error = 'Pairing failed: ${e.code}';
        _busy = false;
      });
    } catch (e) {
      setState(() {
        _error = 'Pairing failed: $e';
        _busy = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (!(Platform.isAndroid || Platform.isIOS)) {
      return Scaffold(
        appBar: AppBar(
          leading: IconButton(
            icon: const Icon(Icons.arrow_back),
            onPressed: () {
              if (Navigator.of(context).canPop()) {
                Navigator.of(context).pop();
              } else {
                GoRouter.of(context).go('/drive');
              }
            },
          ),
          title: const Text('Scan QR'),
        ),
        body: const Center(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Text(
              'Camera scanning is only available on iOS and Android.\nOn desktop, you can paste the pairing token instead (coming soon).',
              textAlign: TextAlign.center,
            ),
          ),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            if (Navigator.of(context).canPop()) {
              Navigator.of(context).pop();
            } else {
              GoRouter.of(context).go('/drive');
            }
          },
        ),
        title: const Text('Scan to pair'),
      ),
      body: Stack(
        children: [
          MobileScanner(
            onDetect: _onDetect,
            controller: MobileScannerController(detectionSpeed: DetectionSpeed.noDuplicates),
          ),
          if (_busy)
            Container(
              color: Colors.black54,
              child: const Center(child: CircularProgressIndicator()),
            ),
          if (_error != null)
            Positioned(
              left: 16,
              right: 16,
              bottom: 24,
              child: Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(color: Colors.red.shade700, borderRadius: BorderRadius.circular(8)),
                child: Text(_error!, style: const TextStyle(color: Colors.white)),
              ),
            ),
        ],
      ),
    );
  }
}
