// XOR-scrambled embedded constants. The plain `strings binary | grep`
// approach finds nothing useful — values are reassembled at runtime from
// two halves XORed together. This is obfuscation, not encryption: a
// determined reverse engineer can still find them, but the bar is raised
// from "trivial" to "trace the assembly".
//
// To rotate either constant: regenerate the scrambled bytes via
// scripts/scramble.dart and replace the lists below.

import 'dart:convert';

class EmbeddedSecrets {
  /// Cryptographic public key of the Weeber license server. Used to verify
  /// every receipt the server issues. A fake server cannot forge tokens
  /// against this key without our private key (which never leaves the VPS).
  static String get licensePublicKeyPem => _decode(_pubKeyA, _pubKeyB);

  /// Canonical API URL. Hardcoded scrambled.
  static String get apiUrl => _decode(_apiUrlA, _apiUrlB);

  /// SHA-256 fingerprint of the API server's TLS certificate, hex-encoded
  /// without colons. Used for pinning. Empty in dev (HTTP); production must
  /// set this to the deployed cert's hash.
  static String get apiCertFingerprint => _decode(_pinA, _pinB);

  // ---------- internals ----------
  static String _decode(List<int> a, List<int> b) {
    final out = List<int>.generate(a.length, (i) => a[i] ^ b[i]);
    return utf8.decode(out);
  }
}

// Generated by `dart run tool/scramble.dart` — do not edit by hand.
// They will be replaced at build time by tooling. The values below are
// initialised lazily in main.dart so that test runs (which import this
// file) don't crash if scrambled bytes haven't been generated yet.
List<int> _pubKeyA = const [];
List<int> _pubKeyB = const [];
List<int> _apiUrlA = const [];
List<int> _apiUrlB = const [];
List<int> _pinA = const [];
List<int> _pinB = const [];

/// Set the scrambled byte pairs at process start. Called from main() with
/// values produced by scramble.dart. Keeping it as a setter (instead of
/// const literals) lets us swap them per-build without touching this file.
void initEmbeddedSecrets({
  required List<int> pubKeyA,
  required List<int> pubKeyB,
  required List<int> apiUrlA,
  required List<int> apiUrlB,
  List<int> pinA = const [],
  List<int> pinB = const [],
}) {
  _pubKeyA = pubKeyA;
  _pubKeyB = pubKeyB;
  _apiUrlA = apiUrlA;
  _apiUrlB = apiUrlB;
  _pinA = pinA;
  _pinB = pinB;
}
